// default-employees.ts
// Export a plain default array (no `id` fields so backend assigns IDs).
// plain JS objects to avoid type import issues.

/** previous format:
 * [
  {
    name: 'Alex Smith',
    position: 'Head of Engineering',
    department: 'Engineering',
    status: 'active',
    imageUrl: '',
    hireDate: '2025-01-01',
  },
 */

const defaultEmployees = [
  {
    name: 'Alex Smith',
    position: 'Head of Engineering',
    department: 'Engineering',
    status: 'active',
    imageUrl: '',
    hireDate: 'hireDate 1',
    id: '1',
  },
  {
    name: 'Jordan Lee',
    position: 'HR Coordinator',
    department: 'Human Resources',
    status: 'active',
    imageUrl: '',
    hireDate: 'hireDate 2',
    id: '2',
  },
  {
    name: 'Taylor Brown',
    position: 'Product Manager',
    department: 'Product',
    status: 'inactive',
    imageUrl: '',
    hireDate: 'hireDate 3',
    id: '3',
  },
  {
    name: 'Casey Johnson',
    position: 'Head of Design',
    department: 'Design',
    status: 'active',
    imageUrl: '',
    hireDate: 'hireDate 4',
    id: '4',
  },
  {
    name: 'Riley Davis',
    position: 'Marketing Specialist',
    department: 'Marketing',
    status: 'inactive',
    imageUrl: '',
    hireDate: 'hireDate 5',
    id: '5',
  },
  {
    name: 'Morgan Wilson',
    position: 'Software Engineer',
    department: 'Engineering',
    status: 'active',
    imageUrl: '',
    hireDate: 'hireDate 6',
    id: '6',
  },
  {
    name: 'Avery Taylor',
    position: 'HR Coordinator',
    department: 'Human Resources',
    status: 'active',
    imageUrl: '',
    hireDate: 'hireDate 7',
    id: '7',
  },
  {
    name: 'Quinn Harris',
    position: 'QA Analyst',
    department: 'Product',
    status: 'inactive',
    imageUrl: '',
    hireDate: 'hireDate 8',
    id: '8',
  },
  {
    name: 'Sage Martinez',
    position: 'UI/UX Designer',
    department: 'Design',
    status: 'active',
    imageUrl: '',
    hireDate: 'hireDate 9',
    id: '9',
  },
  {
    name: 'Rowan Clark',
    position: 'Brand Manager',
    department: 'Marketing',
    status: 'inactive',
    imageUrl: '',
    hireDate: 'hireDate 10',
    id: '10',
  },
  {
    name: 'Emery Lewis',
    position: 'Backend Developer',
    department: 'Engineering',
    status: 'inactive',
    imageUrl: '',
    hireDate: 'hireDate 11',
    id: '11',
  },
  {
    name: 'Skyler Walker',
    position: 'Head of Human Resources',
    department: 'Human Resources',
    status: 'active',
    imageUrl: '',
    hireDate: 'hireDate 12',
    id: '12',
  },
  {
    name: 'Charlie Hall',
    position: 'Product Manager',
    department: 'Product',
    status: 'inactive',
    imageUrl: '',
    hireDate: '2020-11-17',
    id: '13',
  },
  {
    name: 'Finley Allen',
    position: 'UI/UX Designer',
    department: 'Design',
    status: 'active',
    imageUrl: '',
    hireDate: '2022-04-03',
    id: '14',
  },
  {
    name: 'River Young',
    position: 'Head of Marketing',
    department: 'Marketing',
    status: 'inactive',
    imageUrl: '',
    hireDate: '2023-08-28',
    id: '15',
  },
  {
    name: 'Parker King',
    position: 'Frontend Developer',
    department: 'Engineering',
    status: 'active',
    imageUrl: '',
    hireDate: '2020-07-12',
    id: '16',
  },
  {
    name: 'Aspen Wright',
    position: 'Recruiter',
    department: 'Human Resources',
    status: 'active',
    imageUrl: '',
    hireDate: '2021-03-25',
    id: '17',
  },
  {
    name: 'Reese Scott',
    position: 'Head of Product',
    department: 'Product',
    status: 'active',
    imageUrl: '',
    hireDate: '2022-11-08',
    id: '18',
  },
  {
    name: 'Jamie Green',
    position: 'UI/UX Designer',
    department: 'Design',
    status: 'active',
    imageUrl: '',
    hireDate: '2023-05-19',
    id: '19',
  },
  {
    name: 'Kendall Adams',
    position: 'Marketing Specialist',
    department: 'Marketing',
    status: 'active',
    imageUrl: '',
    hireDate: '2021-09-30',
    id: '20',
  },
  {
    name: 'Cameron Baker',
    position: 'Software Engineer',
    department: 'Engineering',
    status: 'active',
    imageUrl: '',
    hireDate: '2020-12-03',
    id: '21',
  },
  {
    name: 'Peyton Cook',
    position: 'HR Coordinator',
    department: 'Human Resources',
    status: 'active',
    imageUrl: '',
    hireDate: '2024-02-14',
    id: '22',
  },
  {
    name: 'Dakota Phillips',
    position: 'QA Analyst',
    department: 'Product',
    status: 'inactive',
    imageUrl: '',
    hireDate: '2022-06-27',
    id: '23',
  },
  {
    name: 'Hayden Turner',
    position: 'UI/UX Designer',
    department: 'Design',
    status: 'active',
    imageUrl: '',
    hireDate: '2021-01-11',
    id: '24',
  },
  {
    name: 'Blake Nelson',
    position: 'Brand Manager',
    department: 'Marketing',
    status: 'active',
    imageUrl: '',
    hireDate: '2023-08-22',
    id: '25',
  },
  {
    name: 'Logan Carter',
    position: 'Backend Developer',
    department: 'Engineering',
    status: 'active',
    imageUrl: '',
    hireDate: '2020-04-05',
    id: '26',
  },
  {
    name: 'Sydney Evans',
    position: 'Recruiter',
    department: 'Human Resources',
    status: 'active',
    imageUrl: '',
    hireDate: '2024-10-17',
    id: '27',
  },
  {
    name: 'Aubrey Mitchell',
    position: 'Product Manager',
    department: 'Product',
    status: 'active',
    imageUrl: '',
    hireDate: '2022-02-28',
    id: '28',
  },
  {
    name: 'Rory Perez',
    position: 'UI/UX Designer',
    department: 'Design',
    status: 'inactive',
    imageUrl: '',
    hireDate: '2021-07-09',
    id: '29',
  },
  {
    name: 'Elliot Foster',
    position: 'Marketing Specialist',
    department: 'Marketing',
    status: 'active',
    imageUrl: '',
    hireDate: '2023-12-01',
    id: '30',
  },
  {
    name: 'Tatum Brooks',
    position: 'Software Engineer',
    department: 'Engineering',
    status: 'active',
    imageUrl: '',
    hireDate: '2020-10-23',
    id: '31',
  },
  {
    name: 'Sage Coleman',
    position: 'HR Coordinator',
    department: 'Human Resources',
    status: 'active',
    imageUrl: '',
    hireDate: '2024-03-15',
    id: '32',
  },
  {
    name: 'Robin Gray',
    position: 'Product Manager',
    department: 'Product',
    status: 'active',
    imageUrl: '',
    hireDate: '2022-09-04',
    id: '33',
  },
  {
    name: 'Jaden Hughes',
    position: 'UI/UX Designer',
    department: 'Design',
    status: 'active',
    imageUrl: '',
    hireDate: '2021-04-20',
    id: '34',
  },
  {
    name: 'Kai Stewart',
    position: 'Marketing Specialist',
    department: 'Marketing',
    status: 'inactive',
    imageUrl: '',
    hireDate: '2023-06-13',
    id: '35',
  },
  {
    name: 'Addison Price',
    position: 'Frontend Developer',
    department: 'Engineering',
    status: 'active',
    imageUrl: '',
    hireDate: '2020-08-07',
    id: '36',
  },
  {
    name: 'Bailey Ward',
    position: 'Recruiter',
    department: 'Human Resources',
    status: 'active',
    imageUrl: '',
    hireDate: '2024-01-29',
    id: '37',
  },
  {
    name: 'Emerson Bell',
    position: 'QA Analyst',
    department: 'Product',
    status: 'active',
    imageUrl: '',
    hireDate: '2022-05-16',
    id: '38',
  },
  {
    name: 'Marley Ross',
    position: 'UI/UX Designer',
    department: 'Design',
    status: 'active',
    imageUrl: '',
    hireDate: '2021-11-02',
    id: '39',
  },
  {
    name: 'Ellis Cooper',
    position: 'Brand Manager',
    department: 'Marketing',
    status: 'inactive',
    imageUrl: '',
    hireDate: '2023-03-08',
    id: '40',
  },
  {
    name: 'Arden James',
    position: 'Backend Developer',
    department: 'Engineering',
    status: 'active',
    imageUrl: '',
    hireDate: '2020-06-21',
    id: '41',
  },
  {
    name: 'Reagan Cox',
    position: 'HR Coordinator',
    department: 'Human Resources',
    status: 'active',
    imageUrl: '',
    hireDate: '2024-07-04',
    id: '42',
  },
  {
    name: 'Lennon Fisher',
    position: 'Product Manager',
    department: 'Product',
    status: 'active',
    imageUrl: '',
    hireDate: '2022-12-19',
    id: '43',
  },
  {
    name: 'Hadley Reed',
    position: 'UI/UX Designer',
    department: 'Design',
    status: 'inactive',
    imageUrl: '',
    hireDate: '2021-02-26',
    id: '44',
  },
  {
    name: 'Sutton Hayes',
    position: 'Marketing Specialist',
    department: 'Marketing',
    status: 'active',
    imageUrl: '',
    hireDate: '2023-09-10',
    id: '45',
  },
  {
    name: 'Phoenix Long',
    position: 'Software Engineer',
    department: 'Engineering',
    status: 'active',
    imageUrl: '',
    hireDate: '2020-03-14',
    id: '46',
  },
  {
    name: 'Remy Stone',
    position: 'Recruiter',
    department: 'Human Resources',
    status: 'inactive',
    imageUrl: '',
    hireDate: '2024-05-22',
    id: '47',
  },
  {
    name: 'Cypress Bennett',
    position: 'QA Analyst',
    department: 'Product',
    status: 'active',
    imageUrl: '',
    hireDate: '2022-07-31',
    id: '48',
  },
  {
    name: 'Harlow Myers',
    position: 'UI/UX Designer',
    department: 'Design',
    status: 'active',
    imageUrl: '',
    hireDate: '2021-10-06',
    id: '49',
  },
  {
    name: 'Juniper Fox',
    position: 'Brand Manager',
    department: 'Marketing',
    status: 'inactive',
    imageUrl: '',
    hireDate: '2023-04-12',
    id: '50',
  },
];

export default defaultEmployees;
